name: Deploy React Site
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy to surge
    steps: 
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/checkout@v2-beta
        with:
          node-version: 12
      
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
        
      - name: Build React App
        run: yarn build
        
      - name: Install Surge
        run: npm install -g surge
        
      - name: Deploy to surge
        run: surge ./build react-app-by-gopaldas.surge.sh --token ${{ secrets.SURGE_TOKEN }}
